#!/bin/bash
#echo "Est-ce que la lumière est allumée?"
#echo "It's `curl --silent http://10.202.255.252/relay/0?turn=off |jq .ison` "
mosquitto_pub -h 10.202.0.107 -t 'shellies/shellyplug-s-6A6534/relay/0/command' -m "off" 
# publie un message sur 10.202.0.107 avec comme topic shellies/shellyplug-s-6A6534/relay/0/command et comme esagge off pour eteindre la prise

echo " La lumière est bien `mosquitto_sub -h 10.202.0.107 -t 'shellies/shellyplug-s-6A6534/relay/0' -C 1` "
# recupere les dernieres info envoyer au broker
#meme commentaire pour shelly_on 
