#!/bin/bash
#echo "Est-ce que la lumière est allumée?"
#echo "It's `curl --silent http://10.202.255.252/relay/0?turn=off |jq .ison` "
mosquitto_pub -h 10.202.0.107 -t 'shellies/shellyplug-s-6A6534/relay/0/command' -m "off"

echo " La lumière est bien `mosquitto_sub -h 10.202.0.107 -t 'shellies/shellyplug-s-6A6534/relay/0' -C 1` "
